export default {
  "login": "errunlee",
  "id": 32530613,
  "node_id": "MDQ6VXNlcjMyNTMwNjEz",
  "avatar_url": "https://avatars.githubusercontent.com/u/32530613?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/errunlee",
  "html_url": "https://github.com/errunlee",
  "followers_url": "https://api.github.com/users/errunlee/followers",
  "following_url": "https://api.github.com/users/errunlee/following{/other_user}",
  "gists_url": "https://api.github.com/users/errunlee/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/errunlee/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/errunlee/subscriptions",
  "organizations_url": "https://api.github.com/users/errunlee/orgs",
  "repos_url": "https://api.github.com/users/errunlee/repos",
  "events_url": "https://api.github.com/users/errunlee/events{/privacy}",
  "received_events_url": "https://api.github.com/users/errunlee/received_events",
  "type": "User",
  "site_admin": false,
  "name": null,
  "company": null,
  "blog": "arunkhatri.com.np",
  "location": null,
  "email": 'akcs4444@gmail.com',
  "hireable": null,
  "bio": "hungry learner",
  "twitter_username": null,
  "public_repos": 37,
  "public_gists": 0,
  "followers": 9,
  "following": 11,
  "created_at": "2017-10-05T01:23:45Z",
  "updated_at": "2023-03-27T11:17:04Z"
}